platform:
  - x64
environment:
  global:
    APPVEYOR_OS_NAME: windows
    RUBY_VERSION: "22-x64"
    GOPATH: c:\gopath
    BINTRAY_USER:
      secure: HvXDg/3xn3Du2GPXPyf1tQ==
    BINTRAY_APIKEY:
      secure: pKFoGMJ1yEvd9hI9yF8a7D5fp5xGt53GdSrV3/g2CVbWiUfNoAXyYzHC1R4jSUqQ
  matrix:
    #- MSYS2_ARCH: x86_64
    #  MSYS2_BITS: 64
    #  MSYSTEM: MSYS2
    #  METHOD: ci
    #- MSYS2_ARCH: i686
    #  MSYS2_BITS: 32
    #  MSYSTEM: MINGW32
    #  METHOD: cross
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      METHOD: cross
      MSYS2_BASEVER: 20150916
install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby -rnet/https -e "Net::HTTP.get URI('https://api.bintray.com')"
  - appveyor DownloadFile https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem
  - appveyor DownloadFile https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Primary_CA.pem
  - appveyor DownloadFile https://www.geotrust.com/resources/root_certificates/certificates/Geotrust_PCA_G3_Root.pem
  - certreq -machine -Accept .\GeoTrust_Global_CA.pem
  - certreq -machine -Accept .\GeoTrust_Primary_CA.pem
  - certreq -machine -Accept .\Geotrust_PCA_G3_Root.pem
  - xcopy .\GeoTrust_Global_CA.pem c:\ssl\certs\
  - xcopy .\GeoTrust_Primary_CA.pem c:\ssl\certs\
  - xcopy .\Geotrust_PCA_G3_Root.pem c:\ssl\certs\
  - SET SSL_CERT_DIR=c:\ssl\certs\
  - ruby -rnet/https -e "Net::HTTP.get URI('https://api.bintray.com')"
  - ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE'
